version: '3.8'

services:
  mailarchive-app:
    build: .
    restart: always
    ports:
      - "5000"
    volumes:
      - ./appsettings.json:/app/appsettings.json
      - ./logs:/app/logs
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - mailarchive-app
    ports:
      - "443:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: MailArchiver
      POSTGRES_USER: mailuser
      POSTGRES_PASSWORD: masterkey
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mail_archiver_user -d MailArchiver"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
