networks:
  postgres:

version: '3.8'

services:
  mailarchive-app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    networks:
      - postgres
    volumes:
      - ./appsettings.json:/app/appsettings.json
      - ./logs:/app/logs
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: MailArchiver
      POSTGRES_USER: mailuser
      POSTGRES_PASSWORD: masterkey
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mailuser -d MailArchiver"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
