name: Bug Report
description: Report a bug or issue with the application
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug!
        Please fill out the form below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of the bug. Include screenshots if necessary.
      placeholder: 'Example: "The export function fails when trying to export more than 1000 emails"'
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Describe the steps to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Application Version
      description: Which version are you using?
      options:
        - "2510.4"
        - "2510.3"
        - "2510.2"
        - "2510.1"
        - "2509.8"
        - "2509.7"
        - "2509.6"
        - "2509.5"
        - "2509.4"
        - "2509.3"
        - "2509.2"
        - "2509.1"
        - "2508.10"
        - "2508.9"
        - "2508.8"
        - "2508.7"
        - "2508.6"
        - "2508.5"
        - "2508.4"
        - "2508.3"
        - "2508.2"
        - "2508.1"
        - "2507.5"
        - "2507.4"
        - "2507.3"
        - "2507.2"
        - "2507.1"
        - "other"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: installation-type
    attributes:
      label: Installation Type
      description: How is the application installed?
      options:
        - "Docker"
        - "Standalone"
        - "Other"
      default: 0
    validations:
      required: false

  - type: input
    id: management-tools
    attributes:
      label: Management Tools
      description: Are Docker management tools in use?
      placeholder: 'e.g., Portainer, etc.'
    validations:
      required: false

  - type: input
    id: host-system
    attributes:
      label: Host System
      description: What is the host operating system?
      placeholder: 'e.g., Ubuntu 24.04, Debian 12, Windows Server 2022, etc.'
    validations:
      required: false

  - type: input
    id: mail-provider
    attributes:
      label: Mail Provider
      description: Which mail provider is being archived?
      placeholder: 'e.g., Mailbox.org, Gmail, etc.'
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: |
        Please copy and paste relevant log output from `docker compose logs`.
        **Important: Ensure proper anonymization of sensitive data (email addresses, domains, credentials, etc.)!**
        Alternatively, you can submit logs via email if they contain sensitive information.
      render: shell
    validations:
      required: true
