name: Feature Request
description: Suggest a new feature or improvement for the application
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
        Please describe your idea in detail so we can evaluate it.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Provide a clear and concise description of the feature you would like to see. Include screenshots or mockups if helpful.
      placeholder: 'Example: "Add support for exporting emails to PDF format with attachments included"'
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working? Describe the desired behavior.
      placeholder: 'Example: "Add an export option that generates a PDF file for each email, including the email content and all attachments bundled together"'
    validations:
      required: false

